import '@styles/index.css';
import type { Metadata } from 'next';
import { cn } from '@lib/class-name';
import { Layout } from '@layout/root';
import type { ReactNode } from 'react';
import { geistSans } from '@lib/text-font';
import { BackTop } from '@components/ui/float-button';
import { ScrollProgressBar } from '@components/ui/page-scroll-progress';

export const metadata: Metadata = {
  title: {
    template: '%s - 寻觅~流光',
    default: '寻觅~流光',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          defer
          src='https://cloud.umami.is/script.js'
          data-website-id='9dcc6b79-11ff-4bb0-b9d3-154bc974b654'
        ></script>
      </head>
      <body
        className={cn(
          'theme-transition',
          'dark:bg-gray-900 dark:text-gray-100',
          'min-h-screen w-full overflow-x-hidden antialiased',
          geistSans.className,
        )}
      >
        <BackTop />
        <ScrollProgressBar />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
