import '@styles/index.css';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Layout } from '@layout/root';
import { Geist, Geist_Mono } from 'next/font/google';
import { BackTop } from '@components/ui/float-button';
import { ScrollProgressBar } from '@components/ui/page-scroll-progress';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s - 8023time',
    default: '8023time 个人网站',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          defer
          src='https://cloud.umami.is/script.js'
          data-website-id='9dcc6b79-11ff-4bb0-b9d3-154bc974b654'
        ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackTop />
        <ScrollProgressBar />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
